version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpass
      POSTGRES_DB: crmdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://crmuser:crmpass@db:5432/crmdb
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  pgdata: